In [1]:
import numpy as np
import polars as pl
import matplotlib.pyplot as plt
import seaborn as sns

plt.style.use('ggplot')

In [2]:
augs = pl.scan_csv("augmenter_setups_4_null.csv").filter(
    pl.all_horizontal(pl.col("Damage", "Rate of Fire", "Shield Max").is_not_null()),
    (pl.col("Electric Tempering") <= 0.0) | (pl.col("Electric Tempering").is_null()),
    ~pl.col("").str.contains("Art of Commanding"),
    ~pl.col("").str.contains("Art of Destruction"),
    ~pl.col("").str.contains("Art of Engineering"),
    ~pl.col("").str.contains("Art of Gunnery"),
    ~pl.col("").str.contains("Art of Healing"),
    ~pl.col("").str.contains("Art of Sharpshooting"),
    ~pl.col("").str.contains("Art of Stealth"),
).collect()
# zeros already replaced with nan

# drop class locked augs
# for aug in ['Ultimate Art of Gunnery']:
#     mask = augs.index.str.contains(aug)
#     augs = augs.loc[~mask]

In [26]:
augs = augs.with_columns(
    dps=(100 * (1 + pl.col("Damage")) * (1 + pl.col("Rate of Fire"))) * (1 + ((0.05 + pl.col("Critical Hit Chance")) * (0.5 * (1 + pl.col("Critical Hit Strength")))))
)

In [4]:
# augs.filter(
#     augs[''].str.contains("Art of Fast Killing") & augs[''].str.contains("The Emperor's Augmenter") & augs[''].str.contains("Grand Navigator")
# )#.select(pl.col("", "rank", *interest, 'Electric Tempering', 'Transference Power'))

# augs.filter(pl.col("").str.contains("""Art of Fast Killing Augmenter', 'Ultimate Art of Fast Killing Augmenter', "The Emperor's Augmenter", "Grand Nav"""))
# augs.filter(pl.col("").str.contains("""Art of Fast Killing Augmenter', 'Ultimate Art of Fast Killing Augmenter', "Grand Navigator's Augmenter", "The Emperor's Augmenter"""))
augs.filter(
    pl.col("").str.contains(""""Grand Navigator's Augmenter", 'Ultimate Art of Fast Killing Augmenter', 'Ultimate Art of Fast Killing Augmenter', "The Emperor's""")
)

shape: (1, 31)
┌───────────────┬──────────┬──────────────┬──────────────┬───┬────────┬─────────┬────────┬─────────┐
│               ┆ Capacity ┆ Critical Hit ┆ Critical Hit ┆ … ┆ Weapon ┆ Weapons ┆ Weight ┆ dps     │
│ ---           ┆ ---      ┆ Chance       ┆ Strength     ┆   ┆ Hold   ┆ Slots   ┆ ---    ┆ ---     │
│ str           ┆ f64      ┆ ---          ┆ ---          ┆   ┆ ---    ┆ ---     ┆ f64    ┆ f64     │
│               ┆          ┆ f64          ┆ f64          ┆   ┆ f64    ┆ f64     ┆        ┆         │
╞═══════════════╪══════════╪══════════════╪══════════════╪═══╪════════╪═════════╪════════╪═════════╡
│ ("Grand       ┆ null     ┆ 0.3          ┆ 0.8          ┆ … ┆ null   ┆ null    ┆ null   ┆ 1012.55 │
│ Navigator's   ┆          ┆              ┆              ┆   ┆        ┆         ┆        ┆         │
│ Augmenter"…   ┆          ┆              ┆              ┆   ┆        ┆         ┆        ┆         │
└───────────────┴──────────┴──────────────┴──────────────┴───┴────────┴─────────┴────────┴─────────┘

In [19]:
a1 = "'Empyreal Rage Augmenter'"
a2 = "'Selenite Augmenter'"
a3 = "'Twisted Tesla Augmenter'"
a4 = "'Ultimate Art of Fast Killing Augmenter'"
augs.filter(
    pl.col("").str.contains(f"{a4}, {a2}, {a1}, {a3}")
)

shape: (0, 30)
┌─────┬──────────┬──────────────┬──────────┬───┬────────────┬─────────────┬─────────┬────────┐
│     ┆ Capacity ┆ Critical Hit ┆ Critical ┆ … ┆ Visibility ┆ Weapon Hold ┆ Weapons ┆ Weight │
│ --- ┆ ---      ┆ Chance       ┆ Hit      ┆   ┆ ---        ┆ ---         ┆ Slots   ┆ ---    │
│ str ┆ f64      ┆ ---          ┆ Strength ┆   ┆ f64        ┆ f64         ┆ ---     ┆ f64    │
│     ┆          ┆ f64          ┆ ---      ┆   ┆            ┆             ┆ f64     ┆        │
│     ┆          ┆              ┆ f64      ┆   ┆            ┆             ┆         ┆        │
╞═════╪══════════╪══════════════╪══════════╪═══╪════════════╪═════════════╪═════════╪════════╡
└─────┴──────────┴──────────────┴──────────┴───┴────────────┴─────────────┴─────────┴────────┘

In [34]:
tmp = augs.filter(
    # pl.col("Critical Hit Chance") >= 0.2,
    pl.col("Critical Hit Strength") >= 1.5,
    # pl.col("Damage") >= 2.0,
    pl.col("Electric Tempering") <= -0.4,
    # pl.col("Energy Max") >= 0.45,
    pl.col("Energy Charge") >= 0.8,
    pl.col("Range") >= 0.5,
    # pl.col("Rate of Fire") >= 2.75,
    pl.col("Resistance to Damage") >= 0.0,
    pl.col("Shield Max") >= 1.0,
    pl.col("Capacity") >= 0.0,
    pl.col("dps") >= 1500
).drop(
    "Docking Speed",
    "Hostility",
    "Inertial Dampening",
    "Multifiring",
    "Projectile Velocity",
    "Radar",
    "Tractor Power",
    "Tractor Range",
    "Visibility",
    "Weapon Hold",
    "Weapons Slots"
).sort("dps", descending=True)

pl.Config.set_fmt_str_lengths(150)
tmp

shape: (3, 20)
┌────────────┬──────────┬────────────┬────────────┬───┬────────────┬─────────┬────────┬────────────┐
│            ┆ Capacity ┆ Critical   ┆ Critical   ┆ … ┆ Transferen ┆ Turning ┆ Weight ┆ dps        │
│ ---        ┆ ---      ┆ Hit Chance ┆ Hit        ┆   ┆ ce Power   ┆ ---     ┆ ---    ┆ ---        │
│ str        ┆ f64      ┆ ---        ┆ Strength   ┆   ┆ ---        ┆ f64     ┆ f64    ┆ f64        │
│            ┆          ┆ f64        ┆ ---        ┆   ┆ f64        ┆         ┆        ┆            │
│            ┆          ┆            ┆ f64        ┆   ┆            ┆         ┆        ┆            │
╞════════════╪══════════╪════════════╪════════════╪═══╪════════════╪═════════╪════════╪════════════╡
│ ('Empyreal ┆ 0.15     ┆ 0.37       ┆ 2.1        ┆ … ┆ null       ┆ 0.2     ┆ null   ┆ 1610.7156  │
│ Rage Augme ┆          ┆            ┆            ┆   ┆            ┆         ┆        ┆            │
│ nter',     ┆          ┆            ┆            ┆   ┆            ┆         ┆        ┆            │
│ 'Luminous  ┆          ┆            ┆            ┆   ┆            ┆         ┆        ┆            │
│ Interstici ┆          ┆            ┆            ┆   ┆            ┆         ┆        ┆            │
│ al         ┆          ┆            ┆            ┆   ┆            ┆         ┆        ┆            │
│ Desistance ┆          ┆            ┆            ┆   ┆            ┆         ┆        ┆            │
│ Augmenter' ┆          ┆            ┆            ┆   ┆            ┆         ┆        ┆            │
│ ,          ┆          ┆            ┆            ┆   ┆            ┆         ┆        ┆            │
│ 'Lustrous  ┆          ┆            ┆            ┆   ┆            ┆         ┆        ┆            │
│ Comminatio ┆          ┆            ┆            ┆   ┆            ┆         ┆        ┆            │
│ n Ambit    ┆          ┆            ┆            ┆   ┆            ┆         ┆        ┆            │
│ Augmenter' ┆          ┆            ┆            ┆   ┆            ┆         ┆        ┆            │
│ , 'Phased  ┆          ┆            ┆            ┆   ┆            ┆         ┆        ┆            │
│ Fortificat ┆          ┆            ┆            ┆   ┆            ┆         ┆        ┆            │
│ ion Augmen ┆          ┆            ┆            ┆   ┆            ┆         ┆        ┆            │
│ ter')      ┆          ┆            ┆            ┆   ┆            ┆         ┆        ┆            │
│ ('Celestia ┆ 0.1      ┆ 0.27       ┆ 2.05       ┆ … ┆ null       ┆ null    ┆ null   ┆ 1540.47701 │
│ l Focus    ┆          ┆            ┆            ┆   ┆            ┆         ┆        ┆ 8          │
│ Augmenter' ┆          ┆            ┆            ┆   ┆            ┆         ┆        ┆            │
│ , 'Total   ┆          ┆            ┆            ┆   ┆            ┆         ┆        ┆            │
│ Eclipse    ┆          ┆            ┆            ┆   ┆            ┆         ┆        ┆            │
│ Illunis    ┆          ┆            ┆            ┆   ┆            ┆         ┆        ┆            │
│ Augmenter' ┆          ┆            ┆            ┆   ┆            ┆         ┆        ┆            │
│ ,          ┆          ┆            ┆            ┆   ┆            ┆         ┆        ┆            │
│ 'Luminous  ┆          ┆            ┆            ┆   ┆            ┆         ┆        ┆            │
│ Obliterati ┆          ┆            ┆            ┆   ┆            ┆         ┆        ┆            │
│ ve         ┆          ┆            ┆            ┆   ┆            ┆         ┆        ┆            │
│ Integrity  ┆          ┆            ┆            ┆   ┆            ┆         ┆        ┆            │
│ Augmenter' ┆          ┆            ┆            ┆   ┆            ┆         ┆        ┆            │
│ , "The     ┆          ┆            ┆            ┆   ┆            ┆         ┆        ┆            │
│ Emperor's  ┆          ┆            ┆            ┆   ┆            ┆         ┆        ┆            │
│ Augmenter" ┆          ┆            ┆            ┆   ┆            ┆         ┆        ┆            │
│ )          ┆          ┆            ┆            ┆   ┆            ┆         ┆        ┆            │
│ ('Luminous ┆ 0.15     ┆ 0.37       ┆ 2.1        ┆ … ┆ null       ┆ 0.2     ┆ null   ┆ 1534.6045  │
│ Interstici ┆          ┆            ┆            ┆   ┆            ┆         ┆        ┆            │
│ al         ┆          ┆            ┆            ┆   ┆            ┆         ┆        ┆            │
│ Desistance ┆          ┆            ┆            ┆   ┆            ┆         ┆        ┆            │
│ Augmenter' ┆          ┆            ┆            ┆   ┆            ┆         ┆        ┆            │
│ ,          ┆          ┆            ┆            ┆   ┆            ┆         ┆        ┆            │
│ 'Lustrous  ┆          ┆            ┆            ┆   ┆            ┆         ┆        ┆            │
│ Comminatio ┆          ┆            ┆            ┆   ┆            ┆         ┆        ┆            │
│ n Ambit    ┆          ┆            ┆            ┆   ┆            ┆         ┆        ┆            │
│ Augmenter' ┆          ┆            ┆            ┆   ┆            ┆         ┆        ┆            │
│ , 'Phased  ┆          ┆            ┆            ┆   ┆            ┆         ┆        ┆            │
│ Fortificat ┆          ┆            ┆            ┆   ┆            ┆         ┆        ┆            │
│ ion Augmen ┆          ┆            ┆            ┆   ┆            ┆         ┆        ┆            │
│ ter', 'Ada ┆          ┆            ┆            ┆   ┆            ┆         ┆        ┆            │
│ manturized ┆          ┆            ┆            ┆   ┆            ┆         ┆        ┆            │
│ Rage       ┆          ┆            ┆            ┆   ┆            ┆         ┆        ┆            │
│ Augmenter… ┆          ┆            ┆            ┆   ┆            ┆         ┆        ┆            │
└────────────┴──────────┴────────────┴────────────┴───┴────────────┴─────────┴────────┴────────────┘

In [19]:
augs.filter(
    # pl.col("Critical Hit Chance") >= 0.2,
    # pl.col("Critical Hit Strength") >= 0.4,
    # pl.col("Damage") >= 2.0,
    pl.col("Electric Tempering") <= -0.4,
    # pl.col("Energy Max") >= 0.45,
    pl.col("Energy Charge") >= 0.5,
    pl.col("Range") >= 0.5,
    # pl.col("Rate of Fire") >= 2.75,
    pl.col("Shield Max") >= 1.0,
    pl.col("Capacity") >= 0.0,
    pl.col("dps") >= 1700
).write_excel("sd_subset.xlsx")

In [21]:
augs2 = pl.scan_csv(
    "augmenter_setups_4_reduced_sd.csv"
).filter(
    pl.all_horizontal(pl.col("Damage", "Rate of Fire", "Shield Max").is_not_null()),
    (pl.col("Electric Tempering") <= 0.0) | (pl.col("Electric Tempering").is_null())
).collect()

In [23]:
augs2 = augs2.with_columns(
    dps=(100 * (1 + pl.col("Damage")) * (1 + pl.col("Rate of Fire"))) * (1 + ((0.05 + pl.col("Critical Hit Chance")) * (0.5 * (1 + pl.col("Critical Hit Strength")))))
)

In [39]:
with pl.Config(fmt_str_lengths=1000, tbl_width_chars=1000, tbl_rows=15):
    display(
        augs2
        .sort("dps", descending=True)
        .filter(
            ~pl.col("").str.contains("Lustrous"),
            ~pl.col("").str.contains("Luminous"),
            ~pl.col("").str.contains("Illunis"),
            ~pl.col("").str.contains("Promontory"),
            pl.col("Shield Max") >= 0.5,
            pl.col("Rate of Fire") < 4,
            pl.col("dps") > 1800,
            pl.col("Critical Hit Strength") >= 1.0,
            pl.col("Electric Tempering") <= -0.3
        )
        .drop(
            "Docking Speed",
            "Hostility",
            "Inertial Dampening",
            # "Multifiring",
            "Projectile Velocity",
            # "Tractor Power",
            # "Tractor Range",
            "Weapon Hold",
            "Weapons Slots"
        )
    )

shape: (8, 22)
┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬──────────┬─────────────────────┬───────────────────────┬───┬─────────┬────────────┬────────┬─────────────┐
│                                                                                                                                             ┆ Capacity ┆ Critical Hit Chance ┆ Critical Hit Strength ┆ … ┆ Turning ┆ Visibility ┆ Weight ┆ dps         │
│ ---                                                                                                                                         ┆ ---      ┆ ---                 ┆ ---                   ┆   ┆ ---     ┆ ---        ┆ ---    ┆ ---         │
│ str                                                                                                                                         ┆ f64      ┆ f64                 ┆ f64                   ┆   ┆ f64     ┆ f64        ┆ f64    ┆ f64         │
╞═════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╪══════════╪═════════════════════╪═══════════════════════╪═══╪═════════╪════════════╪════════╪═════════════╡
│ ('Adamanturized Rage Augmenter', 'Ultimate Art of Fast Killing Augmenter', 'Empyreal Rage Augmenter', 'Heavenly Foresight Augmenter')       ┆ 0.0      ┆ 0.1                 ┆ 1.1                   ┆ … ┆ 0.0     ┆ 0.0        ┆ 0.0    ┆ 1951.834375 │
│ ('Adamanturized Rage Augmenter', 'Adamanturized Rage Augmenter', 'Ultimate Art of Fast Killing Augmenter', 'Heavenly Foresight Augmenter')  ┆ 0.0      ┆ 0.1                 ┆ 1.1                   ┆ … ┆ 0.0     ┆ 0.0        ┆ 0.0    ┆ 1884.41     │
│ ('Adamanturized Rage Augmenter', 'Adamanturized Rage Augmenter', 'Ult. Obliteration Augmenter', "Operative's Accurized Conduits Augmenter") ┆ 0.0      ┆ 0.0                 ┆ 1.0                   ┆ … ┆ 0.0     ┆ 0.5        ┆ 0.0    ┆ 1815.45     │
│ ('Adamanturized Rage Augmenter', 'Adamanturized Rage Augmenter', 'Ult. Assassin Augmenter', 'Lunarian Augmenter')                           ┆ 0.0      ┆ 0.0                 ┆ 1.0                   ┆ … ┆ 0.0     ┆ -0.75      ┆ 0.0    ┆ 1814.4      │
│ ('Lunarian Augmenter', 'Ultimate Art of Fast Killing Augmenter', 'Empyreal Rage Augmenter', "Operative's Cosmic Symmetry Augmenter")        ┆ 0.0      ┆ 0.21                ┆ 1.06                  ┆ … ┆ 0.33    ┆ 0.0        ┆ 0.0    ┆ 1809.315414 │
│ ('Ult. Obliteration Augmenter', "The Emperor's Augmenter", 'Empyreal Rage Augmenter', 'Aberrant Ordnance Augmenter')                        ┆ 0.0      ┆ 0.3                 ┆ 1.0                   ┆ … ┆ 0.0     ┆ 0.0        ┆ 0.0    ┆ 1809.0      │
│ ('Celeste Mark Augmenter', 'Celestial Rage Augmenter', 'Eclipse Augmenter', 'Empyreal Rage Augmenter')                                      ┆ -0.05    ┆ 0.2                 ┆ 1.1                   ┆ … ┆ 0.0     ┆ 0.0        ┆ 0.0    ┆ 1808.215625 │
│ ('Ult. Obliteration Augmenter', "The Emperor's Augmenter", 'Twisted Tesla Augmenter', 'Empyreal Rage Augmenter')                            ┆ 0.0      ┆ 0.2                 ┆ 1.0                   ┆ … ┆ 0.0     ┆ 0.0        ┆ 0.0    ┆ 1800.625    │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴──────────┴─────────────────────┴───────────────────────┴───┴─────────┴────────────┴────────┴─────────────┘