In [1]:
import numpy as np
import polars as pl
import matplotlib.pyplot as plt
import seaborn as sns

plt.style.use('ggplot')

In [2]:
augs = pl.scan_csv("augmenter_setups_4_null.csv").filter(
    pl.all_horizontal(pl.col("Damage", "Rate of Fire", "Shield Max").is_not_null()),
    (pl.col("Electric Tempering") <= 0.0) | (pl.col("Electric Tempering").is_null()),
    ~pl.col("").str.contains("Art of Commanding"),
    ~pl.col("").str.contains("Art of Destruction"),
    ~pl.col("").str.contains("Art of Engineering"),
    ~pl.col("").str.contains("Art of Gunnery"),
    ~pl.col("").str.contains("Art of Healing"),
    ~pl.col("").str.contains("Art of Sharpshooting"),
    ~pl.col("").str.contains("Art of Stealth"),
).collect()
# zeros already replaced with nan

# drop class locked augs
# for aug in ['Ultimate Art of Gunnery']:
#     mask = augs.index.str.contains(aug)
#     augs = augs.loc[~mask]

In [3]:
interest = ('Damage', 'Rate of Fire', 'Critical Hit Chance', 'Critical Hit Strength')

In [4]:
args = (pl.col(""), pl.col(*(i for i in interest if i not in ['Electric Tempering'])).rank(descending=True))
if 'Electric Tempering' in interest:
    args += (pl.col("Electric Tempering").rank(descending=False),)

augs_rank = augs.select(*args)

# fill with 2x size
augs_rank = augs_rank.select(
    pl.all().replace({None: 21e6 * 2})
)

In [5]:
augs_rank = augs_rank.with_columns(
    rank=pl.sum_horizontal(*interest)
)

In [6]:
augs = augs.with_columns(
    rank=augs_rank['rank']
)

In [7]:
with pl.Config(fmt_str_lengths=1000, tbl_width_chars=1000):
    display(augs.select(pl.col('', 'rank', *interest)).sort('rank', descending=False).head(15))

shape: (15, 6)
┌────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬────────────┬────────┬──────────────┬─────────────────────┬───────────────────────┐
│                                                                                                                                                                        ┆ rank       ┆ Damage ┆ Rate of Fire ┆ Critical Hit Chance ┆ Critical Hit Strength │
│ ---                                                                                                                                                                    ┆ ---        ┆ ---    ┆ ---          ┆ ---                 ┆ ---                   │
│ str                                                                                                                                                                    ┆ f64        ┆ f64    ┆ f64          ┆ f64                 ┆ f64                   │
╞════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╪════════════╪════════╪══════════════╪═════════════════════╪═══════════════════════╡
│ ('Celestial Nebulae Augmenter', 'Luminous Obliterative Integrity Augmenter', 'Luminous Obliterative Integrity Augmenter', 'Luminous Obliterative Integrity Augmenter') ┆ 909389.0   ┆ 3.17   ┆ 2.66         ┆ 0.41                ┆ 2.1                   │
│ ('Celestial Nebulae Augmenter', 'Empyreal Rage Augmenter', 'Total Eclipse Illunis Augmenter', 'Luminous Obliterative Integrity Augmenter')                             ┆ 1.08581e6  ┆ 2.84   ┆ 3.07         ┆ 0.37                ┆ 2.05                  │
│ ('Celestial Nebulae Augmenter', 'Total Eclipse Illunis Augmenter', 'Luminous Obliterative Integrity Augmenter', 'Lustrous Mass Despoliation Augmenter')                ┆ 1.106587e6 ┆ 3.04   ┆ 2.77         ┆ 0.37                ┆ 2.05                  │
│ ('Celestial Nebulae Augmenter', 'Total Eclipse Illunis Augmenter', 'Luminous Obliterative Integrity Augmenter', 'Adamanturized Rage Augmenter')                        ┆ 1165729.5  ┆ 2.99   ┆ 2.72         ┆ 0.37                ┆ 2.05                  │
│ ("Qa'ik Urk'qii Akk'oj", 'Empyreal Rage Augmenter', 'Total Eclipse Illunis Augmenter', 'Luminous Obliterative Integrity Augmenter')                                    ┆ 1.180559e6 ┆ 2.89   ┆ 2.57         ┆ 0.37                ┆ 2.65                  │
│ …                                                                                                                                                                      ┆ …          ┆ …      ┆ …            ┆ …                   ┆ …                     │
│ ('Empyreal Rage Augmenter', 'Total Eclipse Illunis Augmenter', 'Luminous Obliterative Integrity Augmenter', 'Lustrous Unalloyed Promontory Augmenter')                 ┆ 1.318817e6 ┆ 3.34   ┆ 2.57         ┆ 0.35                ┆ 2.05                  │
│ ('Celestial Nebulae Augmenter', 'Empyreal Rage Augmenter', 'Total Eclipse Illunis Augmenter', 'Total Eclipse Illunis Augmenter')                                       ┆ 1.326402e6 ┆ 2.8    ┆ 2.35         ┆ 0.4                 ┆ 2.7                   │
│ ('Empyreal Rage Augmenter', 'Luminous Intersticial Desistance Augmenter', 'Luminous Obliterative Integrity Augmenter', 'Luminous Obliterative Integrity Augmenter')    ┆ 1359015.5  ┆ 2.63   ┆ 3.29         ┆ 0.34                ┆ 2.4                   │
│ ('Celestial Nebulae Augmenter', 'Luminous Obliterative Integrity Augmenter', 'Luminous Obliterative Integrity Augmenter', "Operative's Cosmic Symmetry Augmenter")     ┆ 1361905.5  ┆ 2.61   ┆ 2.6          ┆ 0.45                ┆ 2.06                  │
│ ("Qa'ik Vazuk Akk'oj", 'Celestial Nebulae Augmenter', 'Total Eclipse Illunis Augmenter', 'Luminous Obliterative Integrity Augmenter')                                  ┆ 1367438.5  ┆ 2.94   ┆ 2.52         ┆ 0.37                ┆ 2.05                  │
└────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴────────────┴────────┴──────────────┴─────────────────────┴───────────────────────┘

In [17]:
# augs.filter(
#     augs[''].str.contains("Art of Fast Killing") & augs[''].str.contains("The Emperor's Augmenter") & augs[''].str.contains("Grand Navigator")
# )#.select(pl.col("", "rank", *interest, 'Electric Tempering', 'Transference Power'))

# augs.filter(pl.col("").str.contains("""Art of Fast Killing Augmenter', 'Ultimate Art of Fast Killing Augmenter', "The Emperor's Augmenter", "Grand Nav"""))
# augs.filter(pl.col("").str.contains("""Art of Fast Killing Augmenter', 'Ultimate Art of Fast Killing Augmenter', "Grand Navigator's Augmenter", "The Emperor's Augmenter"""))
augs.filter(
    pl.col("").str.contains(""""Grand Navigator's Augmenter", 'Ultimate Art of Fast Killing Augmenter', 'Ultimate Art of Fast Killing Augmenter', "The Emperor's""")
)

shape: (1, 31)
┌──────────────┬──────────┬──────────────┬──────────┬───┬────────┬─────────┬────────┬──────────────┐
│              ┆ Capacity ┆ Critical Hit ┆ Critical ┆ … ┆ Weapon ┆ Weapons ┆ Weight ┆ rank         │
│ ---          ┆ ---      ┆ Chance       ┆ Hit      ┆   ┆ Hold   ┆ Slots   ┆ ---    ┆ ---          │
│ str          ┆ f64      ┆ ---          ┆ Strength ┆   ┆ ---    ┆ ---     ┆ f64    ┆ f64          │
│              ┆          ┆ f64          ┆ ---      ┆   ┆ f64    ┆ f64     ┆        ┆              │
│              ┆          ┆              ┆ f64      ┆   ┆        ┆         ┆        ┆              │
╞══════════════╪══════════╪══════════════╪══════════╪═══╪════════╪═════════╪════════╪══════════════╡
│ ("Grand      ┆ null     ┆ 0.3          ┆ 0.8      ┆ … ┆ null   ┆ null    ┆ null   ┆ 8.853193e6   │
│ Navigator's  ┆          ┆              ┆          ┆   ┆        ┆         ┆        ┆              │
│ Augmenter"…  ┆          ┆              ┆          ┆   ┆        ┆         ┆        ┆              │
└──────────────┴──────────┴──────────────┴──────────┴───┴────────┴─────────┴────────┴──────────────┘

In [19]:
augs.filter(
    pl.col("Critical Hit Chance") >= 0.4,
    pl.col("Critical Hit Strength") >= 0.8,
    pl.col("Damage") >= 1.8,
    pl.col("Electric Tempering") <= -0.4,
    pl.col("Energy Max") >= 0.45,
    pl.col("Range") >= 0.5,
    pl.col("Rate of Fire") >= 1.8,
    pl.col("Shield Max") >= 1.0,
    pl.col("Capacity") >= 0.0,
).drop(
    "Docking Speed",
    "Hostility",
    "Inertial Dampening",
    "Multifiring",
    "Projectile Velocity",
    "Radar",
    "Tractor Power",
    "Tractor Range",
    "Visibility",
    "Weapon Hold",
    "Weapons Slots"
)

shape: (160, 20)
┌────────────┬──────────┬────────────┬────────────┬───┬────────────┬─────────┬────────┬────────────┐
│            ┆ Capacity ┆ Critical   ┆ Critical   ┆ … ┆ Transferen ┆ Turning ┆ Weight ┆ rank       │
│ ---        ┆ ---      ┆ Hit Chance ┆ Hit        ┆   ┆ ce Power   ┆ ---     ┆ ---    ┆ ---        │
│ str        ┆ f64      ┆ ---        ┆ Strength   ┆   ┆ ---        ┆ f64     ┆ f64    ┆ f64        │
│            ┆          ┆ f64        ┆ ---        ┆   ┆ f64        ┆         ┆        ┆            │
│            ┆          ┆            ┆ f64        ┆   ┆            ┆         ┆        ┆            │
╞════════════╪══════════╪════════════╪════════════╪═══╪════════════╪═════════╪════════╪════════════╡
│ ('Divine   ┆ 0.15     ┆ 0.4        ┆ 1.6        ┆ … ┆ null       ┆ null    ┆ null   ┆ 5.029218e6 │
│ Wattage    ┆          ┆            ┆            ┆   ┆            ┆         ┆        ┆            │
│ Augmenter' ┆          ┆            ┆            ┆   ┆            ┆         ┆        ┆            │
│ , "…       ┆          ┆            ┆            ┆   ┆            ┆         ┆        ┆            │
│ ('Divine   ┆ 0.15     ┆ 0.4        ┆ 1.0        ┆ … ┆ null       ┆ null    ┆ null   ┆ 6.319095e6 │
│ Wattage    ┆          ┆            ┆            ┆   ┆            ┆         ┆        ┆            │
│ Augmenter' ┆          ┆            ┆            ┆   ┆            ┆         ┆        ┆            │
│ , "…       ┆          ┆            ┆            ┆   ┆            ┆         ┆        ┆            │
│ ('Divine   ┆ 0.15     ┆ 0.4        ┆ 1.0        ┆ … ┆ null       ┆ null    ┆ null   ┆ 5626861.5  │
│ Wattage    ┆          ┆            ┆            ┆   ┆            ┆         ┆        ┆            │
│ Augmenter' ┆          ┆            ┆            ┆   ┆            ┆         ┆        ┆            │
│ , '…       ┆          ┆            ┆            ┆   ┆            ┆         ┆        ┆            │
│ ('Divine   ┆ 0.15     ┆ 0.4        ┆ 1.0        ┆ … ┆ null       ┆ 0.4     ┆ null   ┆ 5.287046e6 │
│ Wattage    ┆          ┆            ┆            ┆   ┆            ┆         ┆        ┆            │
│ Augmenter' ┆          ┆            ┆            ┆   ┆            ┆         ┆        ┆            │
│ , '…       ┆          ┆            ┆            ┆   ┆            ┆         ┆        ┆            │
│ ('Divine   ┆ 0.15     ┆ 0.4        ┆ 1.0        ┆ … ┆ null       ┆ null    ┆ null   ┆ 5609935.5  │
│ Wattage    ┆          ┆            ┆            ┆   ┆            ┆         ┆        ┆            │
│ Augmenter' ┆          ┆            ┆            ┆   ┆            ┆         ┆        ┆            │
│ , '…       ┆          ┆            ┆            ┆   ┆            ┆         ┆        ┆            │
│ …          ┆ …        ┆ …          ┆ …          ┆ … ┆ …          ┆ …       ┆ …      ┆ …          │
│ ('Luminous ┆ 0.15     ┆ 0.48       ┆ 1.0        ┆ … ┆ null       ┆ null    ┆ 2.0    ┆ 4359771.5  │
│ Interstici ┆          ┆            ┆            ┆   ┆            ┆         ┆        ┆            │
│ al Desist… ┆          ┆            ┆            ┆   ┆            ┆         ┆        ┆            │
│ ('Luminous ┆ 0.15     ┆ 0.4        ┆ 1.0        ┆ … ┆ null       ┆ null    ┆ null   ┆ 4288977.5  │
│ Interstici ┆          ┆            ┆            ┆   ┆            ┆         ┆        ┆            │
│ al Desist… ┆          ┆            ┆            ┆   ┆            ┆         ┆        ┆            │
│ ('Luminous ┆ 0.15     ┆ 0.5        ┆ 1.0        ┆ … ┆ null       ┆ null    ┆ null   ┆ 4.623873e6 │
│ Interstici ┆          ┆            ┆            ┆   ┆            ┆         ┆        ┆            │
│ al Desist… ┆          ┆            ┆            ┆   ┆            ┆         ┆        ┆            │
│ ('Luminous ┆ 0.15     ┆ 0.4        ┆ 1.0        ┆ … ┆ null       ┆ null    ┆ null   ┆ 2.896679e6 │
│ Interstici ┆          ┆            ┆            ┆   ┆            ┆         ┆        ┆            │
│ al Desist… ┆          ┆            ┆            ┆   ┆            ┆         ┆        ┆            │
│ ('Luminous ┆ 0.36     ┆ 0.45       ┆ 1.0        ┆ … ┆ null       ┆ null    ┆ null   ┆ 5.685939e6 │
│ Interstici ┆          ┆            ┆            ┆   ┆            ┆         ┆        ┆            │
│ al Desist… ┆          ┆            ┆            ┆   ┆            ┆         ┆        ┆            │
└────────────┴──────────┴────────────┴────────────┴───┴────────────┴─────────┴────────┴────────────┘

In [21]:
augs.filter(
    pl.col("Critical Hit Chance") >= 0.4,
    pl.col("Critical Hit Strength") >= 0.8,
    pl.col("Damage") >= 1.8,
    pl.col("Electric Tempering") <= -0.4,
    pl.col("Energy Max") >= 0.45,
    pl.col("Range") >= 0.5,
    pl.col("Rate of Fire") >= 1.8,
    pl.col("Shield Max") >= 1.0,
    pl.col("Capacity") >= 0.0,
).write_excel("sd_subset.xlsx")