In [1]:
import numpy as np
import polars as pl
import matplotlib.pyplot as plt
import seaborn as sns

plt.style.use('ggplot')

In [2]:
augs = pl.scan_csv("augmenter_setups_4_reduced.csv").filter(
    pl.all_horizontal(pl.col("Damage", "Rate of Fire", "Shield Max").is_not_null()),
    (pl.col("Electric Tempering") <= 0.0) | (pl.col("Electric Tempering").is_null()),
).collect()

In [3]:
augs = augs.with_columns(
    dps=(100 * (1 + pl.col("Damage")) * (1 + pl.col("Rate of Fire"))) * (1 + ((0.05 + pl.col("Critical Hit Chance")) * (0.5 * (1 + pl.col("Critical Hit Strength")))))
)

In [13]:
augs.filter(
    augs[''].str.contains("Adamanturized Rage") & augs[''].str.contains("The Emperor's Augmenter") & augs[''].str.contains("Vaidya Bhava") & augs[''].str.contains("Nightfury's Patience")
)#.select(pl.col("", "rank", *interest, 'Electric Tempering', 'Transference Power'))

shape: (1, 31)
┌───────────────┬──────────┬───────────────┬──────────────┬───┬────────┬─────────┬────────┬────────┐
│               ┆ Capacity ┆ Critical Hit  ┆ Critical Hit ┆ … ┆ Weapon ┆ Weapons ┆ Weight ┆ dps    │
│ ---           ┆ ---      ┆ Chance        ┆ Strength     ┆   ┆ Hold   ┆ Slots   ┆ ---    ┆ ---    │
│ str           ┆ f64      ┆ ---           ┆ ---          ┆   ┆ ---    ┆ ---     ┆ f64    ┆ f64    │
│               ┆          ┆ f64           ┆ f64          ┆   ┆ f64    ┆ f64     ┆        ┆        │
╞═══════════════╪══════════╪═══════════════╪══════════════╪═══╪════════╪═════════╪════════╪════════╡
│ ("Nightfury's ┆ -0.1     ┆ 0.1           ┆ 0.3          ┆ … ┆ null   ┆ null    ┆ null   ┆ 1229.2 │
│ Patience",    ┆          ┆               ┆              ┆   ┆        ┆         ┆        ┆        │
│ 'Vaid…        ┆          ┆               ┆              ┆   ┆        ┆         ┆        ┆        │
└───────────────┴──────────┴───────────────┴──────────────┴───┴────────┴─────────┴────────┴────────┘

In [9]:
with pl.Config(fmt_str_lengths=1000, tbl_width_chars=1000, tbl_rows=50):
    display(augs.filter(
        pl.col("dps") > 1500,
        pl.col("Range") > 0.5,
        pl.col("Shield Max") >= 1.0,
        pl.col("Shield Recovery") >= 0.5,
        pl.col("Resistance to Damage") >= 0.45,
        # (pl.col("Electric Tempering") <= -0.3) | ((pl.col("Electric Tempering") > 0) & (pl.col("Energy Charge") > 0.5)),
        # pl.col("Energy Max") > 1
        pl.col("Energy Charge") > 0.5
    ).sort("dps", descending=True).drop(
        "Docking Speed",
        "Hostility",
        "Inertial Dampening",
        # "Multifiring",
        "Projectile Velocity",
        # "Tractor Power",
        "Tractor Range",
        "Visibility",
        "Weapon Hold",
        "Weapons Slots"
    )
    )

shape: (2, 21)
┌────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬──────────┬─────────────────────┬───────────────────────┬───┬────────────────────┬─────────┬────────┬────────────┐
│                                                                                                                        ┆ Capacity ┆ Critical Hit Chance ┆ Critical Hit Strength ┆ … ┆ Transference Power ┆ Turning ┆ Weight ┆ dps        │
│ ---                                                                                                                    ┆ ---      ┆ ---                 ┆ ---                   ┆   ┆ ---                ┆ ---     ┆ ---    ┆ ---        │
│ str                                                                                                                    ┆ f64      ┆ f64                 ┆ f64                   ┆   ┆ f64                ┆ f64     ┆ f64    ┆ f64        │
╞════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╪══════════╪═════════════════════╪═══════════════════════╪═══╪════════════════════╪═════════╪════════╪════════════╡
│ ('Selenite Augmenter', "Qa'ik Urk'qii Akk'oj", 'Twisted Tesla Augmenter', 'Luminous Obliterative Integrity Augmenter') ┆ 0.0      ┆ 0.37                ┆ 1.3                   ┆ … ┆ 0.0                ┆ 0.0     ┆ 0.0    ┆ 1644.46904 │
│ ("Qa'ik Urk'qii Akk'oj", 'Deimos Augmenter', 'Twisted Tesla Augmenter', 'Luminous Obliterative Integrity Augmenter')   ┆ 0.0      ┆ 0.37                ┆ 1.3                   ┆ … ┆ 0.0                ┆ 0.0     ┆ 0.0    ┆ 1644.46904 │
└────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴──────────┴─────────────────────┴───────────────────────┴───┴────────────────────┴─────────┴────────┴────────────┘